baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Retro Video Game Fansite'
theme = 'ananke'

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  
[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  
 [[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/" 
 